export default {
  RANDOM_ERROR: 'Got an error!',
  USER_NOT_FOUND: 'User not found!',
  USER_CREATED: 'User created!',
  USER_LOGOUT: 'User logged out!',
  INCORECT_PASS: 'Incorect password!',
  PASS_LENGHT: 'Minimum number of characters 6!',
  REGISTRED_USER_ERROR: 'This user has been registered!',
  INCORECT_EMAIL: 'Incorect email!',
  INCORECT_DATA: 'Incorect data!',
  NOT_AUTHORIZED: 'You are not authorized!',
  SESSION_OUT: 'Session timed out,please login again!',
  INVALID_TOKEN: 'Invalid token,please login again!',
  TYPE_STRING: 'Type of name must be string!',
  INCORECT_CHARTS: 'The name can not contain invalid characters!',
  BOARD_NOT_FOUND: 'Can not find board!',
  COLUMN_NOT_FOUND: 'Can not find column!',
  LEFT_BOARD: 'You have successfully left the board!',
  DELETED_COLUMN: 'Column has been deleted!',
  CARD_DELETED: 'Card has been deleted!',
  CARD_NOT_FOUND: 'Can not find card!',
  INCORECT_POSITION: 'Incorect position!',
  FORBIDDEN_SYMBOLS_REGEXP: /^.*?(?=[\^#%&$\*:<>\?/\{\|\}]).*$/g,
  TOKEN_EXPIRED_ERROR: 'TokenExpiredError',
  WEB_TOKEN_ERROR: 'JsonWebTokenError',
  MISSING_TOKEN: 'Access denied,token missing!',
  TOKEN_EXPIRED: 'Token expired!',
  METHOD_OPTIONS: 'OPTIONS',
  NOT_DELETED: 'Notification has been daleted!',
  USER_INVITED: 'User has already been invited!',
  WELCOME_BOARD: 'Welcome to our board!',
  WILL_GET_INVITE: 'User will get invite!',
}